getopt and shift

diff --git a/create-script b/create-script
--- a/create-script
+++ b/create-script
@@ -10,42 +10,52 @@ if [[ $# -eq 1 ]]; then
 	open_editor="true"
 fi
 
-scriptname="$1"
 declare -r bindir="${HOME}/bin"
-filename="${bindir}/${scriptname}"
-
-#echo "test" > "$filename"
-
-if [[ -e $filename ]]; then
-	echo " File ${filename} already exists"
-fi
-
-if type "$scriptname" > /dev/null 2>&1; then
-	echo "There is already a command with ${scriptname}"
-	exit 1
-fi
 
 #check bin directory exists 
 if [[ ! -d $bindir ]]; then
 	if mkdir "$bindir"; then
-		echo "created ${bindir}"
+		echo "created ${bindir}" >&2
 	else
 
-	 	echo "could not create ${bindir}"
+	 	echo "could not create ${bindir}" >&2
 		exit 1
 	fi
 fi
 
+while [[ $1 ]]; do
+	scriptname="$1"
+	filename="${bindir}/${scriptname}"
+	
+	if [[ -e $filename ]]; then
+		echo " File ${filename} already exists" >&2
+		shift
+		continue
+	fi
 
-#Create script
-echo '#!/bin/bash' >> "$filename"
-# Add exe permission
-chmod u+x "$filename"
+	if type "$scriptname" > /dev/null 2>&1; then
+		echo "There is already a command with ${scriptname}" >&2
+		shift
+		continue
+	fi
+	
+	#Create script
+	echo '#!/bin/bash' >> "$filename"
+	# Add exe permission
+	chmod u+x "$filename"
+
+	shift
+done
+
 #open with editor
-if [[ $EDITOR ]]; then
-	$EDITOR "$filename"
-else
-	echo "script created not startig because we dont have default editor set"
+
+if [[ $open_editor ]]; then
+	echo opening
+	if [[ $EDITOR ]]; then
+		$EDITOR "$filename"
+	else
+		echo "script created not startig because we dont have default editor set" >&2	     fi
+fi
 fi
 
 exit 0
